// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LoxezSpZOOContext.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using LoxezSpZOOContext.Models;

namespace LoxezSpZOOContext.Data
{
    public partial class LoxezSpZOODataContext : DbContext
    {
        public virtual DbSet<Dokument> Dokument { get; set; }
        public virtual DbSet<KoszykElement> KoszykElement { get; set; }
        public virtual DbSet<KoszykNaglowek> KoszykNaglowek { get; set; }

        public LoxezSpZOODataContext(DbContextOptions<LoxezSpZOODataContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Dokument>(entity =>
            {
                entity.Property(e => e.DataUtworzenia).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NazwaPliku).IsUnicode(false);

                entity.Property(e => e.Typ).IsUnicode(false);

                entity.Property(e => e.Tytul).IsUnicode(false);
            });

            modelBuilder.Entity<KoszykElement>(entity =>
            {
                entity.Property(e => e.DataUtworzenia).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Nazwa).IsUnicode(false);

                entity.HasOne(d => d.KoszykNaglowek)
                    .WithMany(p => p.KoszykElement)
                    .HasForeignKey(d => d.KoszykNaglowekId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_KoszykElement_KoszykNaglowekId");
            });

            modelBuilder.Entity<KoszykNaglowek>(entity =>
            {
                entity.Property(e => e.DataUtworzenia).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Sesja).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}