// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GtContext.Models
{
[Table("vwTowar")]
    public partial class VwTowar
    {
        //[Key]
        [Column("tw_Id")]
        public int TwId { get; set; }
        [Column("tw_Zablokowany")]
        public bool TwZablokowany { get; set; }
        [Column("tw_Rodzaj")]
        public int TwRodzaj { get; set; }
        [Required]
        [Column("tw_Symbol")]
        [StringLength(20)]
        public string TwSymbol { get; set; }
        [Required]
        [Column("tw_Nazwa")]
        [StringLength(50)]
        public string TwNazwa { get; set; }
        [Column("st_TowId")]
        public int? StTowId { get; set; }
        [Column("st_MagId")]
        public int? StMagId { get; set; }
        [Column("st_Stan", TypeName = "money")]
        public decimal? StStan { get; set; }
        [Column(TypeName = "money")]
        public decimal? Stan { get; set; }
        [Column(TypeName = "money")]
        public decimal? Rezerwacja { get; set; }
        [Column(TypeName = "money")]
        public decimal? Dostepne { get; set; }
        [Column("st_StanMin", TypeName = "money")]
        public decimal? StStanMin { get; set; }
        [Column("tw_StanMin", TypeName = "money")]
        public decimal? TwStanMin { get; set; }
        [Required]
        [Column("tw_JednMiary")]
        [StringLength(10)]
        public string TwJednMiary { get; set; }
        [Required]
        [Column("tw_Opis")]
        [StringLength(255)]
        public string TwOpis { get; set; }
        [Column("tw_IdVatSp")]
        public int? TwIdVatSp { get; set; }
        [Column("tw_IdVatZak")]
        public int? TwIdVatZak { get; set; }
        [Column("vat_Symbol")]
        [StringLength(20)]
        public string VatSymbol { get; set; }
        [Column("tw_JakPrzySp")]
        public bool TwJakPrzySp { get; set; }
        [Required]
        [Column("tw_PKWiU")]
        [StringLength(20)]
        public string TwPkwiU { get; set; }
        [Required]
        [Column("tw_SWW")]
        [StringLength(20)]
        public string TwSww { get; set; }
        [Column("tw_PLU")]
        public int? TwPlu { get; set; }
        [Column("tw_IdRabat")]
        public int? TwIdRabat { get; set; }
        [Column("tw_IdOpakowanie")]
        public int? TwIdOpakowanie { get; set; }
        [Column("tw_PrzezWartosc")]
        public bool TwPrzezWartosc { get; set; }
        [Column("tw_IdPodstDostawca")]
        public int? TwIdPodstDostawca { get; set; }
        [StringLength(51)]
        public string Dostawca { get; set; }
        [Required]
        [Column("tw_DostSymbol")]
        [StringLength(20)]
        public string TwDostSymbol { get; set; }
        [Column("tw_CzasDostawy")]
        public int? TwCzasDostawy { get; set; }
        [Required]
        [Column("tw_UrzNazwa")]
        [StringLength(50)]
        public string TwUrzNazwa { get; set; }
        [Required]
        [Column("tw_PodstKodKresk")]
        [StringLength(20)]
        public string TwPodstKodKresk { get; set; }
        [Column("tw_IdTypKodu")]
        public int? TwIdTypKodu { get; set; }
        [Column("tw_CenaOtwarta")]
        public bool TwCenaOtwarta { get; set; }
        [Column("tw_WagaEtykiet")]
        public bool? TwWagaEtykiet { get; set; }
        [Column("tw_DniWaznosc")]
        public int? TwDniWaznosc { get; set; }
        [Column("tw_IdGrupa")]
        public int? TwIdGrupa { get; set; }
        [Required]
        [Column("tw_Uwagi")]
        [StringLength(255)]
        public string TwUwagi { get; set; }
        [Required]
        [Column("tw_WWW")]
        [StringLength(255)]
        public string TwWww { get; set; }
        [Column("tw_SklepInternet")]
        public bool TwSklepInternet { get; set; }
        [Column("tw_Charakter", TypeName = "text")]
        public string TwCharakter { get; set; }
        [Column("tw_Logo")]
        [MaxLength(50)]
        public byte[] TwLogo { get; set; }
        [Column("tw_SerwisAukcyjny")]
        public bool TwSerwisAukcyjny { get; set; }
        [Column("tc_CenaNetto1", TypeName = "money")]
        public decimal? TcCenaNetto1 { get; set; }
        [Column("tc_CenaNetto2", TypeName = "money")]
        public decimal? TcCenaNetto2 { get; set; }
        [Column("tc_CenaNetto3", TypeName = "money")]
        public decimal? TcCenaNetto3 { get; set; }
        [Column("tc_CenaNetto4", TypeName = "money")]
        public decimal? TcCenaNetto4 { get; set; }
        [Column("tc_CenaNetto5", TypeName = "money")]
        public decimal? TcCenaNetto5 { get; set; }
        [Column("tc_CenaNetto6", TypeName = "money")]
        public decimal? TcCenaNetto6 { get; set; }
        [Column("tc_CenaNetto7", TypeName = "money")]
        public decimal? TcCenaNetto7 { get; set; }
        [Column("tc_CenaNetto8", TypeName = "money")]
        public decimal? TcCenaNetto8 { get; set; }
        [Column("tc_CenaNetto9", TypeName = "money")]
        public decimal? TcCenaNetto9 { get; set; }
        [Column("tc_CenaNetto10", TypeName = "money")]
        public decimal? TcCenaNetto10 { get; set; }
        [Column("tc_CenaBrutto1", TypeName = "money")]
        public decimal? TcCenaBrutto1 { get; set; }
        [Column("tc_CenaBrutto2", TypeName = "money")]
        public decimal? TcCenaBrutto2 { get; set; }
        [Column("tc_CenaBrutto3", TypeName = "money")]
        public decimal? TcCenaBrutto3 { get; set; }
        [Column("tc_CenaBrutto4", TypeName = "money")]
        public decimal? TcCenaBrutto4 { get; set; }
        [Column("tc_CenaBrutto5", TypeName = "money")]
        public decimal? TcCenaBrutto5 { get; set; }
        [Column("tc_CenaBrutto6", TypeName = "money")]
        public decimal? TcCenaBrutto6 { get; set; }
        [Column("tc_CenaBrutto7", TypeName = "money")]
        public decimal? TcCenaBrutto7 { get; set; }
        [Column("tc_CenaBrutto8", TypeName = "money")]
        public decimal? TcCenaBrutto8 { get; set; }
        [Column("tc_CenaBrutto9", TypeName = "money")]
        public decimal? TcCenaBrutto9 { get; set; }
        [Column("tc_CenaBrutto10", TypeName = "money")]
        public decimal? TcCenaBrutto10 { get; set; }
        [Column("tc_IdTowar")]
        public int? TcIdTowar { get; set; }
        [Column("tc_Zysk1", TypeName = "money")]
        public decimal? TcZysk1 { get; set; }
        [Column("tc_Zysk2", TypeName = "money")]
        public decimal? TcZysk2 { get; set; }
        [Column("tc_Zysk3", TypeName = "money")]
        public decimal? TcZysk3 { get; set; }
        [Column("tc_Zysk4", TypeName = "money")]
        public decimal? TcZysk4 { get; set; }
        [Column("tc_Zysk5", TypeName = "money")]
        public decimal? TcZysk5 { get; set; }
        [Column("tc_Zysk6", TypeName = "money")]
        public decimal? TcZysk6 { get; set; }
        [Column("tc_Zysk7", TypeName = "money")]
        public decimal? TcZysk7 { get; set; }
        [Column("tc_Zysk8", TypeName = "money")]
        public decimal? TcZysk8 { get; set; }
        [Column("tc_Zysk9", TypeName = "money")]
        public decimal? TcZysk9 { get; set; }
        [Column("tc_Zysk10", TypeName = "money")]
        public decimal? TcZysk10 { get; set; }
        [Column("tc_Narzut1", TypeName = "money")]
        public decimal? TcNarzut1 { get; set; }
        [Column("tc_Narzut2", TypeName = "money")]
        public decimal? TcNarzut2 { get; set; }
        [Column("tc_Narzut3", TypeName = "money")]
        public decimal? TcNarzut3 { get; set; }
        [Column("tc_Narzut4", TypeName = "money")]
        public decimal? TcNarzut4 { get; set; }
        [Column("tc_Narzut5", TypeName = "money")]
        public decimal? TcNarzut5 { get; set; }
        [Column("tc_Narzut6", TypeName = "money")]
        public decimal? TcNarzut6 { get; set; }
        [Column("tc_Narzut7", TypeName = "money")]
        public decimal? TcNarzut7 { get; set; }
        [Column("tc_Narzut8", TypeName = "money")]
        public decimal? TcNarzut8 { get; set; }
        [Column("tc_Narzut9", TypeName = "money")]
        public decimal? TcNarzut9 { get; set; }
        [Column("tc_Narzut10", TypeName = "money")]
        public decimal? TcNarzut10 { get; set; }
        [Column("tc_Marza1", TypeName = "money")]
        public decimal? TcMarza1 { get; set; }
        [Column("tc_Marza2", TypeName = "money")]
        public decimal? TcMarza2 { get; set; }
        [Column("tc_Marza3", TypeName = "money")]
        public decimal? TcMarza3 { get; set; }
        [Column("tc_Marza4", TypeName = "money")]
        public decimal? TcMarza4 { get; set; }
        [Column("tc_Marza5", TypeName = "money")]
        public decimal? TcMarza5 { get; set; }
        [Column("tc_Marza6", TypeName = "money")]
        public decimal? TcMarza6 { get; set; }
        [Column("tc_Marza7", TypeName = "money")]
        public decimal? TcMarza7 { get; set; }
        [Column("tc_Marza8", TypeName = "money")]
        public decimal? TcMarza8 { get; set; }
        [Column("tc_Marza9", TypeName = "money")]
        public decimal? TcMarza9 { get; set; }
        [Column("tc_Marza10", TypeName = "money")]
        public decimal? TcMarza10 { get; set; }
        [Column("tc_IdWaluta1")]
        [StringLength(3)]
        public string TcIdWaluta1 { get; set; }
        [Column("tc_IdWaluta2")]
        [StringLength(3)]
        public string TcIdWaluta2 { get; set; }
        [Column("tc_IdWaluta3")]
        [StringLength(3)]
        public string TcIdWaluta3 { get; set; }
        [Column("tc_IdWaluta4")]
        [StringLength(3)]
        public string TcIdWaluta4 { get; set; }
        [Column("tc_IdWaluta5")]
        [StringLength(3)]
        public string TcIdWaluta5 { get; set; }
        [Column("tc_IdWaluta6")]
        [StringLength(3)]
        public string TcIdWaluta6 { get; set; }
        [Column("tc_IdWaluta7")]
        [StringLength(3)]
        public string TcIdWaluta7 { get; set; }
        [Column("tc_IdWaluta8")]
        [StringLength(3)]
        public string TcIdWaluta8 { get; set; }
        [Column("tc_IdWaluta9")]
        [StringLength(3)]
        public string TcIdWaluta9 { get; set; }
        [Column("tc_IdWaluta10")]
        [StringLength(3)]
        public string TcIdWaluta10 { get; set; }
        [Column("tc_CenaNetto0", TypeName = "money")]
        public decimal? TcCenaNetto0 { get; set; }
        [Column("tc_WalutaId")]
        [StringLength(3)]
        public string TcWalutaId { get; set; }
        [Column("tc_WalutaKurs", TypeName = "money")]
        public decimal? TcWalutaKurs { get; set; }
        [Column("tc_PodstawaKC")]
        public int? TcPodstawaKc { get; set; }
        [Column("tc_CenaNettoWaluta", TypeName = "money")]
        public decimal? TcCenaNettoWaluta { get; set; }
        [Column("tc_WalutaJedn")]
        [StringLength(10)]
        public string TcWalutaJedn { get; set; }
        [Required]
        [Column("tw_Pole1")]
        [StringLength(50)]
        public string TwPole1 { get; set; }
        [Required]
        [Column("tw_Pole2")]
        [StringLength(50)]
        public string TwPole2 { get; set; }
        [Required]
        [Column("tw_Pole3")]
        [StringLength(50)]
        public string TwPole3 { get; set; }
        [Required]
        [Column("tw_Pole4")]
        [StringLength(50)]
        public string TwPole4 { get; set; }
        [Required]
        [Column("tw_Pole5")]
        [StringLength(50)]
        public string TwPole5 { get; set; }
        [Required]
        [Column("tw_Pole6")]
        [StringLength(50)]
        public string TwPole6 { get; set; }
        [Required]
        [Column("tw_Pole7")]
        [StringLength(50)]
        public string TwPole7 { get; set; }
        [Required]
        [Column("tw_Pole8")]
        [StringLength(50)]
        public string TwPole8 { get; set; }
        [Column("tw_SprzedazMobilna")]
        public bool TwSprzedazMobilna { get; set; }
        [Column("tw_Wysokosc", TypeName = "money")]
        public decimal? TwWysokosc { get; set; }
        [Column("tw_Szerokosc", TypeName = "money")]
        public decimal? TwSzerokosc { get; set; }
        [Column("tw_Glebokosc", TypeName = "money")]
        public decimal? TwGlebokosc { get; set; }
        [Column("tw_StanMaks", TypeName = "money")]
        public decimal? TwStanMaks { get; set; }
        [Column("tw_ObrotMarza")]
        public bool TwObrotMarza { get; set; }
        [Column("tw_OdwrotneObciazenie")]
        public bool TwOdwrotneObciazenie { get; set; }
        [Column("tw_MechanizmPodzielonejPlatnosci")]
        public bool TwMechanizmPodzielonejPlatnosci { get; set; }
        [Column("tw_KodTowaru")]
        [StringLength(8)]
        public string TwKodTowaru { get; set; }
    }
}