// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GtContext.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using GtContext.Models;

namespace GtContext.Data
{
    public partial class GtDataContext : DbContext
    {
        public virtual DbSet<VwTowar> VwTowar { get; set; }

        public GtDataContext(DbContextOptions<GtDataContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VwTowar>(entity =>
            {
                entity.HasNoKey();
                //entity.HasKey(k => new { k.TwId });

                entity.ToView("vwTowar");

                entity.Property(e => e.Dostawca).IsUnicode(false);

                entity.Property(e => e.TcIdWaluta1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.TcIdWaluta10)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.TcIdWaluta2)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.TcIdWaluta3)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.TcIdWaluta4)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.TcIdWaluta5)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.TcIdWaluta6)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.TcIdWaluta7)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.TcIdWaluta8)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.TcIdWaluta9)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.TcWalutaId)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.TcWalutaJedn).IsUnicode(false);

                entity.Property(e => e.TwDostSymbol).IsUnicode(false);

                entity.Property(e => e.TwJednMiary).IsUnicode(false);

                entity.Property(e => e.TwKodTowaru).IsUnicode(false);

                entity.Property(e => e.TwLogo).IsFixedLength();

                entity.Property(e => e.TwNazwa).IsUnicode(false);

                entity.Property(e => e.TwOpis).IsUnicode(false);

                entity.Property(e => e.TwPkwiU).IsUnicode(false);

                entity.Property(e => e.TwPodstKodKresk).IsUnicode(false);

                entity.Property(e => e.TwPole1).IsUnicode(false);

                entity.Property(e => e.TwPole2).IsUnicode(false);

                entity.Property(e => e.TwPole3).IsUnicode(false);

                entity.Property(e => e.TwPole4).IsUnicode(false);

                entity.Property(e => e.TwPole5).IsUnicode(false);

                entity.Property(e => e.TwPole6).IsUnicode(false);

                entity.Property(e => e.TwPole7).IsUnicode(false);

                entity.Property(e => e.TwPole8).IsUnicode(false);

                entity.Property(e => e.TwSww).IsUnicode(false);

                entity.Property(e => e.TwSymbol).IsUnicode(false);

                entity.Property(e => e.TwUrzNazwa).IsUnicode(false);

                entity.Property(e => e.TwUwagi).IsUnicode(false);

                entity.Property(e => e.TwWww).IsUnicode(false);

                entity.Property(e => e.VatSymbol).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}