// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LoxezSpZOOContext.Models
{
    public partial class KoszykElement
    {
        [Key]
        public int Id { get; set; }
        public int KoszykNaglowekId { get; set; }
        [Required]
        public string Nazwa { get; set; }
        [Column(TypeName = "money")]
        public decimal Ilosc { get; set; }
        [Column(TypeName = "money")]
        public decimal Cena { get; set; }
        public int? TwTowarTwId { get; set; }
        [Column(TypeName = "date")]
        public DateTime DataUtworzenia { get; set; }

        [ForeignKey("KoszykNaglowekId")]
        [InverseProperty("KoszykElement")]
        public virtual KoszykNaglowek KoszykNaglowek { get; set; }
    }
}