// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LoxezSpZOOContext.Models
{
    public partial class KoszykNaglowek
    {
        public KoszykNaglowek()
        {
            KoszykElement = new HashSet<KoszykElement>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string Sesja { get; set; }
        [Column(TypeName = "date")]
        public DateTime DataUtworzenia { get; set; }

        [InverseProperty("KoszykNaglowek")]
        public virtual ICollection<KoszykElement> KoszykElement { get; set; }
    }
}